/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    Contract,
    ContractTransaction,
    Overrides,
    CallOverrides,
  } from "ethers";
  import { BytesLike } from "@ethersproject/bytes";
  import { Listener, Provider } from "@ethersproject/providers";
  import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
  import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";
  
  interface LiquidityProtectionStoreInterface extends ethers.utils.Interface {
    functions: {
      "acceptOwnership()": FunctionFragment;
      "addLockedBalance(address,uint256,uint256)": FunctionFragment;
      "addPoolToWhitelist(address)": FunctionFragment;
      "addProtectedLiquidity(address,address,address,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
      "decSystemBalance(address,uint256)": FunctionFragment;
      "incSystemBalance(address,uint256)": FunctionFragment;
      "isPoolWhitelisted(address)": FunctionFragment;
      "lockedBalance(address,uint256)": FunctionFragment;
      "lockedBalanceCount(address)": FunctionFragment;
      "lockedBalanceRange(address,uint256,uint256)": FunctionFragment;
      "newOwner()": FunctionFragment;
      "owner()": FunctionFragment;
      "protectedLiquidity(uint256)": FunctionFragment;
      "protectedLiquidityCount(address)": FunctionFragment;
      "protectedLiquidityId(address,uint256)": FunctionFragment;
      "protectedLiquidityIds(address)": FunctionFragment;
      "removeLockedBalance(address,uint256)": FunctionFragment;
      "removePoolFromWhitelist(address)": FunctionFragment;
      "removeProtectedLiquidity(uint256)": FunctionFragment;
      "systemBalance(address)": FunctionFragment;
      "totalProtectedPoolAmount(address)": FunctionFragment;
      "totalProtectedReserveAmount(address,address)": FunctionFragment;
      "transferOwnership(address)": FunctionFragment;
      "updateProtectedLiquidityAmounts(uint256,uint256,uint256)": FunctionFragment;
      "whitelistedPool(uint256)": FunctionFragment;
      "whitelistedPoolCount()": FunctionFragment;
      "whitelistedPools()": FunctionFragment;
      "withdrawTokens(address,address,uint256)": FunctionFragment;
    };
  
    encodeFunctionData(
      functionFragment: "acceptOwnership",
      values?: undefined
    ): string;
    encodeFunctionData(
      functionFragment: "addLockedBalance",
      values: [string, BigNumberish, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "addPoolToWhitelist",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "addProtectedLiquidity",
      values: [
        string,
        string,
        string,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ): string;
    encodeFunctionData(
      functionFragment: "decSystemBalance",
      values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "incSystemBalance",
      values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "isPoolWhitelisted",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "lockedBalance",
      values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "lockedBalanceCount",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "lockedBalanceRange",
      values: [string, BigNumberish, BigNumberish]
    ): string;
    encodeFunctionData(functionFragment: "newOwner", values?: undefined): string;
    encodeFunctionData(functionFragment: "owner", values?: undefined): string;
    encodeFunctionData(
      functionFragment: "protectedLiquidity",
      values: [BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "protectedLiquidityCount",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "protectedLiquidityId",
      values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "protectedLiquidityIds",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "removeLockedBalance",
      values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "removePoolFromWhitelist",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "removeProtectedLiquidity",
      values: [BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "systemBalance",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "totalProtectedPoolAmount",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "totalProtectedReserveAmount",
      values: [string, string]
    ): string;
    encodeFunctionData(
      functionFragment: "transferOwnership",
      values: [string]
    ): string;
    encodeFunctionData(
      functionFragment: "updateProtectedLiquidityAmounts",
      values: [BigNumberish, BigNumberish, BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "whitelistedPool",
      values: [BigNumberish]
    ): string;
    encodeFunctionData(
      functionFragment: "whitelistedPoolCount",
      values?: undefined
    ): string;
    encodeFunctionData(
      functionFragment: "whitelistedPools",
      values?: undefined
    ): string;
    encodeFunctionData(
      functionFragment: "withdrawTokens",
      values: [string, string, BigNumberish]
    ): string;
  
    decodeFunctionResult(
      functionFragment: "acceptOwnership",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "addLockedBalance",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "addPoolToWhitelist",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "addProtectedLiquidity",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "decSystemBalance",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "incSystemBalance",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "isPoolWhitelisted",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "lockedBalance",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "lockedBalanceCount",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "lockedBalanceRange",
      data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "newOwner", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
    decodeFunctionResult(
      functionFragment: "protectedLiquidity",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "protectedLiquidityCount",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "protectedLiquidityId",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "protectedLiquidityIds",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "removeLockedBalance",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "removePoolFromWhitelist",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "removeProtectedLiquidity",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "systemBalance",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "totalProtectedPoolAmount",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "totalProtectedReserveAmount",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "transferOwnership",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "updateProtectedLiquidityAmounts",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "whitelistedPool",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "whitelistedPoolCount",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "whitelistedPools",
      data: BytesLike
    ): Result;
    decodeFunctionResult(
      functionFragment: "withdrawTokens",
      data: BytesLike
    ): Result;
  
    events: {
      "BalanceLocked(address,uint256,uint256)": EventFragment;
      "BalanceUnlocked(address,uint256)": EventFragment;
      "OwnerUpdate(address,address)": EventFragment;
      "PoolWhitelistUpdated(address,bool)": EventFragment;
      "ProtectionAdded(address,address,address,uint256,uint256)": EventFragment;
      "ProtectionRemoved(address,address,address,uint256,uint256)": EventFragment;
      "ProtectionUpdated(address,uint256,uint256,uint256,uint256)": EventFragment;
      "SystemBalanceUpdated(address,uint256,uint256)": EventFragment;
    };
  
    getEvent(nameOrSignatureOrTopic: "BalanceLocked"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "BalanceUnlocked"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "OwnerUpdate"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "PoolWhitelistUpdated"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "ProtectionAdded"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "ProtectionRemoved"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "ProtectionUpdated"): EventFragment;
    getEvent(nameOrSignatureOrTopic: "SystemBalanceUpdated"): EventFragment;
  }
  
  export class LiquidityProtectionStore extends Contract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;
  
    listeners<EventArgsArray extends Array<any>, EventArgsObject>(
      eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
    ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
    off<EventArgsArray extends Array<any>, EventArgsObject>(
      eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
      listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this;
    on<EventArgsArray extends Array<any>, EventArgsObject>(
      eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
      listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this;
    once<EventArgsArray extends Array<any>, EventArgsObject>(
      eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
      listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this;
    removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
      eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
      listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this;
    removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
      eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
    ): this;
  
    listeners(eventName?: string): Array<Listener>;
    off(eventName: string, listener: Listener): this;
    on(eventName: string, listener: Listener): this;
    once(eventName: string, listener: Listener): this;
    removeListener(eventName: string, listener: Listener): this;
    removeAllListeners(eventName?: string): this;
  
    queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
      event: TypedEventFilter<EventArgsArray, EventArgsObject>,
      fromBlockOrBlockhash?: string | number | undefined,
      toBlock?: string | number | undefined
    ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;
  
    interface: LiquidityProtectionStoreInterface;
  
    functions: {
      acceptOwnership(
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "acceptOwnership()"(
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      addLockedBalance(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "addLockedBalance(address,uint256,uint256)"(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      addPoolToWhitelist(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "addPoolToWhitelist(address)"(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      addProtectedLiquidity(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "addProtectedLiquidity(address,address,address,uint256,uint256,uint256,uint256,uint256)"(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      decSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "decSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      incSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "incSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      isPoolWhitelisted(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<[boolean]>;
  
      "isPoolWhitelisted(address)"(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<[boolean]>;
  
      lockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber, BigNumber]>;
  
      "lockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber, BigNumber]>;
  
      lockedBalanceCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      "lockedBalanceCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      lockedBalanceRange(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber[], BigNumber[]]>;
  
      "lockedBalanceRange(address,uint256,uint256)"(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber[], BigNumber[]]>;
  
      newOwner(overrides?: CallOverrides): Promise<[string]>;
  
      "newOwner()"(overrides?: CallOverrides): Promise<[string]>;
  
      owner(overrides?: CallOverrides): Promise<[string]>;
  
      "owner()"(overrides?: CallOverrides): Promise<[string]>;
  
      protectedLiquidity(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ]
      >;
  
      "protectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ]
      >;
  
      protectedLiquidityCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      "protectedLiquidityCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      protectedLiquidityId(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      "protectedLiquidityId(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      protectedLiquidityIds(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber[]]>;
  
      "protectedLiquidityIds(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber[]]>;
  
      removeLockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "removeLockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      removePoolFromWhitelist(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "removePoolFromWhitelist(address)"(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      removeProtectedLiquidity(
        _id: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "removeProtectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      systemBalance(
        _token: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      "systemBalance(address)"(
        _token: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      totalProtectedPoolAmount(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      "totalProtectedPoolAmount(address)"(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      totalProtectedReserveAmount(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      "totalProtectedReserveAmount(address,address)"(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<[BigNumber]>;
  
      transferOwnership(
        _newOwner: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "transferOwnership(address)"(
        _newOwner: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      updateProtectedLiquidityAmounts(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "updateProtectedLiquidityAmounts(uint256,uint256,uint256)"(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      whitelistedPool(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[string]>;
  
      "whitelistedPool(uint256)"(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[string]>;
  
      whitelistedPoolCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  
      "whitelistedPoolCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  
      whitelistedPools(overrides?: CallOverrides): Promise<[string[]]>;
  
      "whitelistedPools()"(overrides?: CallOverrides): Promise<[string[]]>;
  
      withdrawTokens(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
  
      "withdrawTokens(address,address,uint256)"(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<ContractTransaction>;
    };
  
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "acceptOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    addLockedBalance(
      _provider: string,
      _amount: BigNumberish,
      _expirationTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "addLockedBalance(address,uint256,uint256)"(
      _provider: string,
      _amount: BigNumberish,
      _expirationTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    addPoolToWhitelist(
      _poolAnchor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "addPoolToWhitelist(address)"(
      _poolAnchor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    addProtectedLiquidity(
      _provider: string,
      _poolToken: string,
      _reserveToken: string,
      _poolAmount: BigNumberish,
      _reserveAmount: BigNumberish,
      _reserveRateN: BigNumberish,
      _reserveRateD: BigNumberish,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "addProtectedLiquidity(address,address,address,uint256,uint256,uint256,uint256,uint256)"(
      _provider: string,
      _poolToken: string,
      _reserveToken: string,
      _poolAmount: BigNumberish,
      _reserveAmount: BigNumberish,
      _reserveRateN: BigNumberish,
      _reserveRateD: BigNumberish,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    decSystemBalance(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "decSystemBalance(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    incSystemBalance(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "incSystemBalance(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    isPoolWhitelisted(
      _poolAnchor: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  
    "isPoolWhitelisted(address)"(
      _poolAnchor: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  
    lockedBalance(
      _provider: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  
    "lockedBalance(address,uint256)"(
      _provider: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  
    lockedBalanceCount(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    "lockedBalanceCount(address)"(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    lockedBalanceRange(
      _provider: string,
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[]]>;
  
    "lockedBalanceRange(address,uint256,uint256)"(
      _provider: string,
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[]]>;
  
    newOwner(overrides?: CallOverrides): Promise<string>;
  
    "newOwner()"(overrides?: CallOverrides): Promise<string>;
  
    owner(overrides?: CallOverrides): Promise<string>;
  
    "owner()"(overrides?: CallOverrides): Promise<string>;
  
    protectedLiquidity(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;
  
    "protectedLiquidity(uint256)"(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ]
    >;
  
    protectedLiquidityCount(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    "protectedLiquidityCount(address)"(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    protectedLiquidityId(
      _provider: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    "protectedLiquidityId(address,uint256)"(
      _provider: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    protectedLiquidityIds(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  
    "protectedLiquidityIds(address)"(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  
    removeLockedBalance(
      _provider: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "removeLockedBalance(address,uint256)"(
      _provider: string,
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    removePoolFromWhitelist(
      _poolAnchor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "removePoolFromWhitelist(address)"(
      _poolAnchor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    removeProtectedLiquidity(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "removeProtectedLiquidity(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    systemBalance(_token: string, overrides?: CallOverrides): Promise<BigNumber>;
  
    "systemBalance(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    totalProtectedPoolAmount(
      _poolToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    "totalProtectedPoolAmount(address)"(
      _poolToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    totalProtectedReserveAmount(
      _poolToken: string,
      _reserveToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    "totalProtectedReserveAmount(address,address)"(
      _poolToken: string,
      _reserveToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  
    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    updateProtectedLiquidityAmounts(
      _id: BigNumberish,
      _newPoolAmount: BigNumberish,
      _newReserveAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "updateProtectedLiquidityAmounts(uint256,uint256,uint256)"(
      _id: BigNumberish,
      _newPoolAmount: BigNumberish,
      _newReserveAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    whitelistedPool(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  
    "whitelistedPool(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  
    whitelistedPoolCount(overrides?: CallOverrides): Promise<BigNumber>;
  
    "whitelistedPoolCount()"(overrides?: CallOverrides): Promise<BigNumber>;
  
    whitelistedPools(overrides?: CallOverrides): Promise<string[]>;
  
    "whitelistedPools()"(overrides?: CallOverrides): Promise<string[]>;
  
    withdrawTokens(
      _token: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    "withdrawTokens(address,address,uint256)"(
      _token: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  
    callStatic: {
      acceptOwnership(overrides?: CallOverrides): Promise<void>;
  
      "acceptOwnership()"(overrides?: CallOverrides): Promise<void>;
  
      addLockedBalance(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "addLockedBalance(address,uint256,uint256)"(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      addPoolToWhitelist(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "addPoolToWhitelist(address)"(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<void>;
  
      addProtectedLiquidity(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "addProtectedLiquidity(address,address,address,uint256,uint256,uint256,uint256,uint256)"(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      decSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "decSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      incSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "incSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      isPoolWhitelisted(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<boolean>;
  
      "isPoolWhitelisted(address)"(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<boolean>;
  
      lockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber, BigNumber]>;
  
      "lockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber, BigNumber]>;
  
      lockedBalanceCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "lockedBalanceCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      lockedBalanceRange(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber[], BigNumber[]]>;
  
      "lockedBalanceRange(address,uint256,uint256)"(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<[BigNumber[], BigNumber[]]>;
  
      newOwner(overrides?: CallOverrides): Promise<string>;
  
      "newOwner()"(overrides?: CallOverrides): Promise<string>;
  
      owner(overrides?: CallOverrides): Promise<string>;
  
      "owner()"(overrides?: CallOverrides): Promise<string>;
  
      protectedLiquidity(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ]
      >;
  
      "protectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<
        [
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ]
      >;
  
      protectedLiquidityCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "protectedLiquidityCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      protectedLiquidityId(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "protectedLiquidityId(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      protectedLiquidityIds(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber[]>;
  
      "protectedLiquidityIds(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber[]>;
  
      removeLockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "removeLockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      removePoolFromWhitelist(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "removePoolFromWhitelist(address)"(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<void>;
  
      removeProtectedLiquidity(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "removeProtectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      systemBalance(
        _token: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "systemBalance(address)"(
        _token: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      totalProtectedPoolAmount(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "totalProtectedPoolAmount(address)"(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      totalProtectedReserveAmount(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "totalProtectedReserveAmount(address,address)"(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      transferOwnership(
        _newOwner: string,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "transferOwnership(address)"(
        _newOwner: string,
        overrides?: CallOverrides
      ): Promise<void>;
  
      updateProtectedLiquidityAmounts(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "updateProtectedLiquidityAmounts(uint256,uint256,uint256)"(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      whitelistedPool(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<string>;
  
      "whitelistedPool(uint256)"(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<string>;
  
      whitelistedPoolCount(overrides?: CallOverrides): Promise<BigNumber>;
  
      "whitelistedPoolCount()"(overrides?: CallOverrides): Promise<BigNumber>;
  
      whitelistedPools(overrides?: CallOverrides): Promise<string[]>;
  
      "whitelistedPools()"(overrides?: CallOverrides): Promise<string[]>;
  
      withdrawTokens(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
  
      "withdrawTokens(address,address,uint256)"(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: CallOverrides
      ): Promise<void>;
    };
  
    filters: {
      BalanceLocked(
        _provider: string | null,
        _amount: null,
        _expirationTime: null
      ): TypedEventFilter<
        [string, BigNumber, BigNumber],
        { _provider: string; _amount: BigNumber; _expirationTime: BigNumber }
      >;
  
      BalanceUnlocked(
        _provider: string | null,
        _amount: null
      ): TypedEventFilter<
        [string, BigNumber],
        { _provider: string; _amount: BigNumber }
      >;
  
      OwnerUpdate(
        _prevOwner: string | null,
        _newOwner: string | null
      ): TypedEventFilter<
        [string, string],
        { _prevOwner: string; _newOwner: string }
      >;
  
      PoolWhitelistUpdated(
        _poolAnchor: string | null,
        _added: null
      ): TypedEventFilter<
        [string, boolean],
        { _poolAnchor: string; _added: boolean }
      >;
  
      ProtectionAdded(
        _provider: string | null,
        _poolToken: string | null,
        _reserveToken: string | null,
        _poolAmount: null,
        _reserveAmount: null
      ): TypedEventFilter<
        [string, string, string, BigNumber, BigNumber],
        {
          _provider: string;
          _poolToken: string;
          _reserveToken: string;
          _poolAmount: BigNumber;
          _reserveAmount: BigNumber;
        }
      >;
  
      ProtectionRemoved(
        _provider: string | null,
        _poolToken: string | null,
        _reserveToken: string | null,
        _poolAmount: null,
        _reserveAmount: null
      ): TypedEventFilter<
        [string, string, string, BigNumber, BigNumber],
        {
          _provider: string;
          _poolToken: string;
          _reserveToken: string;
          _poolAmount: BigNumber;
          _reserveAmount: BigNumber;
        }
      >;
  
      ProtectionUpdated(
        _provider: string | null,
        _prevPoolAmount: null,
        _prevReserveAmount: null,
        _newPoolAmount: null,
        _newReserveAmount: null
      ): TypedEventFilter<
        [string, BigNumber, BigNumber, BigNumber, BigNumber],
        {
          _provider: string;
          _prevPoolAmount: BigNumber;
          _prevReserveAmount: BigNumber;
          _newPoolAmount: BigNumber;
          _newReserveAmount: BigNumber;
        }
      >;
  
      SystemBalanceUpdated(
        _token: null,
        _prevAmount: null,
        _newAmount: null
      ): TypedEventFilter<
        [string, BigNumber, BigNumber],
        { _token: string; _prevAmount: BigNumber; _newAmount: BigNumber }
      >;
    };
  
    estimateGas: {
      acceptOwnership(
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "acceptOwnership()"(
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      addLockedBalance(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "addLockedBalance(address,uint256,uint256)"(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      addPoolToWhitelist(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "addPoolToWhitelist(address)"(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      addProtectedLiquidity(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "addProtectedLiquidity(address,address,address,uint256,uint256,uint256,uint256,uint256)"(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      decSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "decSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      incSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "incSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      isPoolWhitelisted(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "isPoolWhitelisted(address)"(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      lockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "lockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      lockedBalanceCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "lockedBalanceCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      lockedBalanceRange(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "lockedBalanceRange(address,uint256,uint256)"(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      newOwner(overrides?: CallOverrides): Promise<BigNumber>;
  
      "newOwner()"(overrides?: CallOverrides): Promise<BigNumber>;
  
      owner(overrides?: CallOverrides): Promise<BigNumber>;
  
      "owner()"(overrides?: CallOverrides): Promise<BigNumber>;
  
      protectedLiquidity(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "protectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      protectedLiquidityCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "protectedLiquidityCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      protectedLiquidityId(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "protectedLiquidityId(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      protectedLiquidityIds(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "protectedLiquidityIds(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      removeLockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "removeLockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      removePoolFromWhitelist(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "removePoolFromWhitelist(address)"(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      removeProtectedLiquidity(
        _id: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "removeProtectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      systemBalance(
        _token: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "systemBalance(address)"(
        _token: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      totalProtectedPoolAmount(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "totalProtectedPoolAmount(address)"(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      totalProtectedReserveAmount(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "totalProtectedReserveAmount(address,address)"(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      transferOwnership(
        _newOwner: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "transferOwnership(address)"(
        _newOwner: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      updateProtectedLiquidityAmounts(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "updateProtectedLiquidityAmounts(uint256,uint256,uint256)"(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      whitelistedPool(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      "whitelistedPool(uint256)"(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<BigNumber>;
  
      whitelistedPoolCount(overrides?: CallOverrides): Promise<BigNumber>;
  
      "whitelistedPoolCount()"(overrides?: CallOverrides): Promise<BigNumber>;
  
      whitelistedPools(overrides?: CallOverrides): Promise<BigNumber>;
  
      "whitelistedPools()"(overrides?: CallOverrides): Promise<BigNumber>;
  
      withdrawTokens(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
  
      "withdrawTokens(address,address,uint256)"(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<BigNumber>;
    };
  
    populateTransaction: {
      acceptOwnership(
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "acceptOwnership()"(
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      addLockedBalance(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "addLockedBalance(address,uint256,uint256)"(
        _provider: string,
        _amount: BigNumberish,
        _expirationTime: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      addPoolToWhitelist(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "addPoolToWhitelist(address)"(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      addProtectedLiquidity(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "addProtectedLiquidity(address,address,address,uint256,uint256,uint256,uint256,uint256)"(
        _provider: string,
        _poolToken: string,
        _reserveToken: string,
        _poolAmount: BigNumberish,
        _reserveAmount: BigNumberish,
        _reserveRateN: BigNumberish,
        _reserveRateD: BigNumberish,
        _timestamp: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      decSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "decSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      incSystemBalance(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "incSystemBalance(address,uint256)"(
        _token: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      isPoolWhitelisted(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "isPoolWhitelisted(address)"(
        _poolAnchor: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      lockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "lockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      lockedBalanceCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "lockedBalanceCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      lockedBalanceRange(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "lockedBalanceRange(address,uint256,uint256)"(
        _provider: string,
        _startIndex: BigNumberish,
        _endIndex: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      newOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  
      "newOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  
      owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  
      "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  
      protectedLiquidity(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "protectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      protectedLiquidityCount(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "protectedLiquidityCount(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      protectedLiquidityId(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "protectedLiquidityId(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      protectedLiquidityIds(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "protectedLiquidityIds(address)"(
        _provider: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      removeLockedBalance(
        _provider: string,
        _index: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "removeLockedBalance(address,uint256)"(
        _provider: string,
        _index: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      removePoolFromWhitelist(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "removePoolFromWhitelist(address)"(
        _poolAnchor: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      removeProtectedLiquidity(
        _id: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "removeProtectedLiquidity(uint256)"(
        _id: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      systemBalance(
        _token: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "systemBalance(address)"(
        _token: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      totalProtectedPoolAmount(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "totalProtectedPoolAmount(address)"(
        _poolToken: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      totalProtectedReserveAmount(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "totalProtectedReserveAmount(address,address)"(
        _poolToken: string,
        _reserveToken: string,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      transferOwnership(
        _newOwner: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "transferOwnership(address)"(
        _newOwner: string,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      updateProtectedLiquidityAmounts(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "updateProtectedLiquidityAmounts(uint256,uint256,uint256)"(
        _id: BigNumberish,
        _newPoolAmount: BigNumberish,
        _newReserveAmount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      whitelistedPool(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "whitelistedPool(uint256)"(
        _index: BigNumberish,
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      whitelistedPoolCount(
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      "whitelistedPoolCount()"(
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      whitelistedPools(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  
      "whitelistedPools()"(
        overrides?: CallOverrides
      ): Promise<PopulatedTransaction>;
  
      withdrawTokens(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
  
      "withdrawTokens(address,address,uint256)"(
        _token: string,
        _to: string,
        _amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
      ): Promise<PopulatedTransaction>;
    };
  }
  